export const subscriptionList = {
    "errors": false,
    "data": {
    "success": "sucess",
    "message": "Plan found",
    "result": [
    {
    "id": 198,
    "name": "30  Car Automatic 30 Hrs Beginner",
    "arabic_name": "30  Car Automatic 30 Hrs Beginner",
    "description": "<p>30 &nbsp;Car Automatic 30 Hrs Beginner</p>",
    "arabic_description": "<p>30 &nbsp;Car Automatic 30 Hrs Beginner</p>",
    "gender": 0,
    "school_id": 71,
    "min_age": 17,
    "total_hrs": 32,
    "total_amount": "2685.00",
    "currency": null,
    "license_type_id": 191,
    "sub_license_id": 192,
    "sub_license_lv1_id": null,
    "sub_license_lv2_id": null,
    "sub_license_lv3_id": null,
    "plan_type": "main_plan",
    "gear_type": 1,
    "plan_type_id": 1,
    "status": 1,
    "online_registration_allowed": 0,
    "no_of_wl_restrict_for_register": 2500,
    "mandatory_sequence": 1,
    "components": [
    "{\"compid\":\"308\",\"order\":308,\"name\":\"Theory Beginner 6 Hrs (30 Hrs)\",\"component_type\":1}",
    "{\"compid\":\"309\",\"order\":309,\"name\":\"Simulator 2 Hrs (30 Hrs)\",\"component_type\":2}",
    "{\"compid\":\"310\",\"order\":310,\"name\":\"Theory Exam\",\"component_type\":3}",
    "{\"compid\":\"311\",\"order\":311,\"name\":\"Practical Training 22 Hrs (30 Hrs)\",\"component_type\":4}",
    "{\"compid\":\"312\",\"order\":312,\"name\":\"Practical Exam\",\"component_type\":5}"
    ],
    "no_of_missed_sessions": 1,
    "level_id": 1,
    "deleted_at": null,
    "created_at": "2022-11-06T08:47:40.000000Z",
    "updated_at": "2022-11-06T08:47:40.000000Z",
    "title": "30  Car Automatic 30 Hrs Beginner",
    "duration": 32,
    "price": "2685.00"
    },
    {
    "id": 199,
    "name": "Car Automatic 15 Hrs Intermediate",
    "arabic_name": "Car Automatic 15 Hrs Intermediate",
    "description": "<p>Car Automatic 15 Hrs Intermediate</p>",
    "arabic_description": "<p>Car Automatic 15 Hrs Intermediate</p>",
    "gender": 0,
    "school_id": 71,
    "min_age": 17,
    "total_hrs": 13,
    "total_amount": "1128.00",
    "currency": null,
    "license_type_id": 191,
    "sub_license_id": 192,
    "sub_license_lv1_id": null,
    "sub_license_lv2_id": null,
    "sub_license_lv3_id": null,
    "plan_type": "main_plan",
    "gear_type": 1,
    "plan_type_id": 1,
    "status": 1,
    "online_registration_allowed": 0,
    "no_of_wl_restrict_for_register": 2500,
    "mandatory_sequence": 1,
    "components": [
    "{\"compid\":\"313\",\"order\":313,\"name\":\"Theory 4 Hrs (15 hrs)\",\"component_type\":1}",
    "{\"compid\":\"314\",\"order\":314,\"name\":\"Simulator 1 Hrs (15 hrs)\",\"component_type\":2}",
    "{\"compid\":\"310\",\"order\":310,\"name\":\"Theory Exam\",\"component_type\":3}",
    "{\"compid\":\"315\",\"order\":315,\"name\":\"Practical Training 10 hrs(15 hrs)\",\"component_type\":4}",
    "{\"compid\":\"312\",\"order\":312,\"name\":\"Practical Exam\",\"component_type\":5}"
    ],
    "no_of_missed_sessions": 1,
    "level_id": 2,
    "deleted_at": null,
    "created_at": "2022-11-06T08:50:02.000000Z",
    "updated_at": "2022-11-06T08:50:02.000000Z",
    "title": "Car Automatic 15 Hrs Intermediate",
    "duration": 13,
    "price": "1128.00"
    },
    {
    "id": 200,
    "name": "Car Automatic 6 hrs (advanced)",
    "arabic_name": "Car Automatic 6 hrs (advanced)",
    "description": "<p>Car Automatic 6 hrs (advanced)</p>",
    "arabic_description": "<p>Car Automatic 6 hrs (advanced)</p>",
    "gender": 0,
    "school_id": 71,
    "min_age": 17,
    "total_hrs": 10,
    "total_amount": "802.50",
    "currency": null,
    "license_type_id": 191,
    "sub_license_id": 192,
    "sub_license_lv1_id": null,
    "sub_license_lv2_id": null,
    "sub_license_lv3_id": null,
    "plan_type": "main_plan",
    "gear_type": 1,
    "plan_type_id": 1,
    "status": 1,
    "online_registration_allowed": 0,
    "no_of_wl_restrict_for_register": 2500,
    "mandatory_sequence": 1,
    "components": [
    "{\"compid\":\"316\",\"order\":316,\"name\":\"Theory 4 Hrs (6 hr)\",\"component_type\":1}",
    "{\"compid\":\"310\",\"order\":310,\"name\":\"Theory Exam\",\"component_type\":3}",
    "{\"compid\":\"317\",\"order\":317,\"name\":\"Practical 4 Hrs (6 hrs)\",\"component_type\":4}",
    "{\"compid\":\"312\",\"order\":312,\"name\":\"Practical Exam\",\"component_type\":5}"
    ],
    "no_of_missed_sessions": 1,
    "level_id": 3,
    "deleted_at": null,
    "created_at": "2022-11-06T08:51:28.000000Z",
    "updated_at": "2022-11-06T08:51:28.000000Z",
    "title": "Car Automatic 6 hrs (advanced)",
    "duration": 10,
    "price": "802.50"
    },
    {
    "id": 201,
    "name": "Evalauation",
    "arabic_name": "Evalauation",
    "description": "<p>Evalauation</p>",
    "arabic_description": "<p>Evalauation</p>",
    "gender": 0,
    "school_id": 71,
    "min_age": 17,
    "total_hrs": 0,
    "total_amount": "0.00",
    "currency": null,
    "license_type_id": 191,
    "sub_license_id": 192,
    "sub_license_lv1_id": null,
    "sub_license_lv2_id": null,
    "sub_license_lv3_id": null,
    "plan_type": null,
    "gear_type": 1,
    "plan_type_id": 2,
    "status": 1,
    "online_registration_allowed": 0,
    "no_of_wl_restrict_for_register": 2500,
    "mandatory_sequence": 1,
    "components": [
    "{\"compid\":\"318\",\"order\":318,\"name\":\"Evalauation\",\"component_type\":5}"
    ],
    "no_of_missed_sessions": 1,
    "level_id": 2,
    "deleted_at": null,
    "created_at": "2022-11-06T08:53:04.000000Z",
    "updated_at": "2022-11-06T08:53:04.000000Z",
    "title": "Evalauation",
    "duration": 0,
    "price": "0.00"
    },
    {
    "id": 203,
    "name": "Subh- Beginner-Theory- Regular- Plan",
    "arabic_name": "Subh- Beginner-Theory- Regular- Plan",
    "description": "<p>Subh- Beginner-Theory- Regular- Plan</p>",
    "arabic_description": "<p>Subh- Beginner-Theory- Regular- Plan</p>",
    "gender": 0,
    "school_id": 71,
    "min_age": 18,
    "total_hrs": 16,
    "total_amount": "1262.50",
    "currency": null,
    "license_type_id": 191,
    "sub_license_id": 192,
    "sub_license_lv1_id": 47,
    "sub_license_lv2_id": null,
    "sub_license_lv3_id": null,
    "plan_type": "main_plan",
    "gear_type": 1,
    "plan_type_id": 1,
    "status": 1,
    "online_registration_allowed": 0,
    "no_of_wl_restrict_for_register": 100,
    "mandatory_sequence": 1,
    "components": [
    "{\"compid\":\"319\",\"order\":319,\"name\":\"Subh- Beginner-Theory- Regular\",\"component_type\":1}",
    "{\"compid\":\"315\",\"order\":315,\"name\":\"Practical Training 10 hrs(15 hrs)\",\"component_type\":4}"
    ],
    "no_of_missed_sessions": 0,
    "level_id": 1,
    "deleted_at": null,
    "created_at": "2022-11-08T06:20:22.000000Z",
    "updated_at": "2022-11-08T06:20:22.000000Z",
    "title": "Subh- Beginner-Theory- Regular- Plan",
    "duration": 16,
    "price": "1262.50"
    }
    ]
    },
    "status_code": 200
    }
